### ISSUE TITLE
data.csv is missing

### ISSUE THREAD

**Issue by pemagrg1** [amanthedorkknight/News-Sentiment-Analysis#1]
in extract_sentiment.ipynb you have used data.csv but the file is not there in the project.
Wha does data.csv contains? news articles?

**Comment by 4m4n5** [comment]
Yes. The file data.csv contains the news articles that is generated by the extract_articles.ipynb. 
Although in the final iteration of the project I changed the name of the generated file to data_final.csv. 

You can comfortably replace 'data.csv' with 'data_final.csv' to proceed with extract_sentiment.ipynb. 

Thanks for pointing out the issue.
